FOGL-1773 sense HAT plugin code added with debian package structure
foglamp/foglamp-south-sensehat pull request #1
Opened 2018-08-31 11:15 UTC by ashish-jabble

**Features**

The Sense HAT features an 8x8 RGB LED matrix, a mini joystick and the following sensors:

- [x] Gyroscope
- [x] Accelerometer
- [x] Magnetometer
- [x] Temperature
- [x] Humidity
- [x] Barometric pressure

Do we really need to implement 8x8 RGB LED and joystick implementation?

2018-08-31 11:34 UTC, praveen-garg requested changes

2018-08-31 11:34 UTC, praveen-garg commented on packages/Debian/armhf/DEBIAN/preinst
> +#!/bin/sh
remove this

2018-08-31 11:34 UTC, praveen-garg commented on python/foglamp/plugins/south/sensehat/sensehat.py
> +_LOGGER = logger.setup(__name__, level=20)
always better to import logging and set level=logging.INFO

2018-08-31 11:34 UTC, praveen-garg commented on python/foglamp/plugins/south/sensehat/sensehat.py
> +    sense = SenseHat()
could you please make it `if not sense: sense = SenseHat()`

2018-08-31 11:34 UTC, praveen-garg commented on python/foglamp/plugins/south/sensehat/sensehat.py
> +        _LOGGER.exception("Sense HAT exception: {}".format(str(ex)))
I suggest to handle `RuntimeError as e` in other block, you don't need str(ex). always use %s for logger

2018-08-31 11:34 UTC, praveen-garg commented on python/foglamp/plugins/south/sensehat/sensehat.py
> +    it should be called when the configuration of the plugin is changed during the operation of the South device service;
`device` -> `plugin`

2018-08-31 11:34 UTC, praveen-garg commented on python/foglamp/plugins/south/sensehat/sensehat.py
> +def _str_to_bool(s):
move it as internal def of `plugin_poll`

2018-08-31 14:59 UTC, billehunt commented
re: Do we really need to implement 8x8 RGB LED and joystick implementation?

For now, no. However, @MarkRiddoch, we should think about how to fit control into our architecture.

2018-09-01 03:43 UTC, billehunt commented
Actually, please implement joystick as the API returns: {"direction": "up", "action": "pressed"}.

Functionally, this looks great. Please resolve the feedback called out in this PR and commit it to the develop branch ASAP.

2018-09-01 11:46 UTC, ashish-jabble commented
@billehunt @praveen-garg feedback changes incorporated and joystick feature implemented.

2018-09-01 12:24 UTC, praveen-garg approved these changes

2018-09-01 12:24 UTC, merged

2018-09-01 12:25 UTC, praveen-garg commented
Merging ASAP. 
May be we need to  handle removal of `preinstl` script and debian package test later!